name: Deploy to HF Spaces

on:
  push:
    branches: [ main ]
    paths:
      - 'deployment/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r deployment/requirements.txt
        pip install huggingface_hub
    
    - name: Login to Hugging Face
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        huggingface-cli login --token $HF_TOKEN
    
    - name: Deploy to Spaces
      run: |
        cd deployment
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git clone https://huggingface.co/spaces/${{ secrets.HF_USERNAME }}/imagenet-classifier space
        cp -r app.py requirements.txt README.md model.ckpt imagenet_classes.json examples space/
        cd space
        git add .
        git commit -m "Update deployment"
        git push 